<?php

namespace Database\Seeders;

use App\Models\Laboratorio;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LaboratorioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $scriptlab = "INSERT INTO LABORATORIOS(cod_arancel,NOMBRE,area_cod)
        VALUES
        (1,'COMBS DIRECTO',1),
        (2,'COMBS INDIRECTO',1),
        (3,'ERITROSEDIMENTACION',1),
        (4,'GRUPO SANGUINEO',1),
        (5,'HEMOGRAMA',1),
        (6,'HEMATOCRITO',1),
        (7,'INVESTIGACION CELULAS LE',1),
        (8,'INVESTIGACION PLASMODIUM',1),
        (9,'RECUENTO DE PLAQUETAS',1),
        (10,'RECUENTO DE RETICULOCITOS',1),
        (11,'COAGULOGRAMA',1),
        (12,'T. PROTROMBINA TESTIGO',1),
        (13,'T.PARCIAL DE TROMBPL. ACTIVA',1),
        (14,'HEMOGLOBINA',1),
        (15,'STROUTH',1),
        (16,'TIEMPO DE COAGULACION (TC)',1),

        (18,'TIEMPO DE SANGRIA (TS)',1),
        (19,'ESPERMOGRAMA',1),

        (20,'CITOGRAMA NASAL',1),
        (21,'CITOGRAMA LAGRIMAL',1),

        (23,'GASOMETRIA',1),
        (24,'FIBRINOGENO',1),
        (25,'CITOQUIMICO',1),
        (26,'OBSERVACIONES',1),

        (33,'ESPERMOGRAMA',1),

        (35,'FROTIS PERIFERICO',1),


        (1,'GLICEMIA BASAL',2),
        (2,'UREA',2),
        (3,'CREATININA',2),
        (4,'ACIDO URICO',2),
        (5,'IONOGRAMA',2),
        (6,'CLORO',2),
        (7,'CALCIO SERICO',2),
        (8,'CALCIO IONICO',2),
        (9,'FOSFORO',2),
        (10,'MAGNESIO',2),
        (11,'PROTEINOGRAMA',2),
        (12,'ALBUMINA',2),
        (13,'AMILASA',2),
        (14,'ALFA AMILASA',2),
        (15,'TRANSAMINASA',2),
        (16,'FOSFATASA ALCALINA',2),
        (17,'GGT GAMA GLUTAMIL TRANSFERASA',2),
        (18,'BILIRRUBINA NEONATAL :',2),
        (19,'BILIRUBINAS',2),
        (20,'PERFIL LIPIDICO',2),
        (21,'COLESTEROL',2),
        (22,'TRIGLICERIDOS',2),
        (23,'LDH',2),
        (24,'CPK',2),
        (25,'CK-MB',2),
        (26,'TROPONINA',2),
        (27,'MIOGLOBINA',2),
        (28,'GLICEMIA POST PRANDIAL',2),
        (29,'CURVA DE TOLERANCIA',2),
        (30,'CK-MB HASTA 25',2),
        (31,'POTASIO EN ORINA',2),
        (32,'CALCIO IONICO',2),
        (33,'CLORO EN ORINA',2),
        (34,'ALFA AMILASA',2),
        (36,'PROTEINAS EN ORINA CASUAL',2),
        (37,'CREATINURIA EN ORINA CASUAL',2),
        (38,'LIPASA',2),
        (39,'TROPONINA T',2),
        (41,'CREATININA DE LIQUIDO PERITONEAL :',2),
        (42,'MIOGLOBINA',2),
        (43,'GLICEMIA DE LIQUIDO PERITONEAL',2),
        (44,'FOSFATASA ALCALINA(DIASYS)',2),
        (45,'SODIO EN ORINA',2),
        (46,'HEPATOGRAMA',2),
        (48,'ALBUMINA',2),
        (49,'DIMERO- D',2),
        (50,'OBSERVACIONES',2),
        (51,'FOSFATASA ALCALINA(NINOS)',2),
        (57,'POTASIO EN ORINA CASUAL',2),
        (58,'SODIO EN ORINA CASUAL',2),
        (60,'GLISEMIA',2),
        (61,'OSMOLARIADAD URINARIA',2),
        (62,'DIMERO D',2),






        (1,'REACCION DE VDRL NEGATIVO',3),
        (2,'ASTO (ANTIESTREPTOLISINA O)',3),
        (3,'HEPATITIS VIRAL',3),
        (4,'HEMOAGLUTINACION IN. CHAGAS',3),
        (5,'PERFIL REMATOIDEO',3),
        (6,'ENA',3),
        (7,'ANA SCREEN',3),
        (8,'ANA HEP-2 (IFI)',3),
        (9,'PSA (ELISA)',3),
        (10,'PROTEINA C.REACTIVA',3),
        (11,'HBSAG (ANTRIGENO SUPERFICIE HB)',3),
        (12,'ELISA-HIV 1/2(AG/AC)',3),
        (13,'REACCION DE WIDAL',3),
        (14,'R.DE WEIL FELIX',3),
        (15,'EPSTEIN-BARR',3),
        (16,'PRUEBA RAPIDA ANTICUERPOS',3),
        (17,'ANTI-MITOCONDRIAL  IFI(AMA)',3),
        (18,'REACCION DE VDRL',3),
        (19,'ANTI DS DNA',3),
        (20,'ANTI- SM',3),
        (21,'ELECTROFORESIS',3),
        (22,'HB. GLICOSILADA A1C',3),
        (23,'FACTOR REUMATOIDEO (LATEX)',3),
        (24,'DOSIFICACION DE COMPLEMENTO (C3 - C4)',3),
        (25,'ANTI.RBD-IGG(COVID-19)',3),
        (27,'HIV - PRUEBA RAPIDA',3),
        (28,'HERPES SIMPLE 1',3),
        (29,'HERPES SIMPLE 2',3),
        (30,'INMUNOGLOBULINA (IGG)',3),
        (31,'INMUNOGLOBULINA (IGM)',3),
        (32,'INMUNOGLOBULINA (IGA)',3),
        (33,'RUBEOLA',3),
        (34,'HERPES SIMPLE 1 Y 2           NTU',3),
        (35,'CISTICERCOSIS',3),
        (36,'HB. GLICOSILADA A1C........',3),
        (37,'CHAGAS IGG - ELISA',3),
        (38,'STROUTH',3),
        (39,'ANTI CCP3',3),
        (40,'CITOMEGALOVIRUS',3),
        (41,'TSH NEONATAL (ELISA)',3),
        (42,'DENGUE',3),
        (43,'ANCA',3),
        (51,'TEST PACK',3),
        (52,'CHIKUNGUNYA',3),
        (53,'ANTI-MUSCULOLISO IFI (ASMA)',3),
        (54,'BRUSELOSIS',3),
        (55,'H1N1',3),
        (56,'HEPATITIS A',3),
        (57,'HEPATITIS B',3),
        (58,'HEPATITIS C',3),
        (59,'TOXO IGM',3),
        (60,'TOXO IGG',3),
        (61,'ZIKA',3),
        (62,'LEPTOSPIROSIS',3),
        (63,'MICROALBUMINURIA',3),
        (64,'TACROLIMUS (LIA)',3),
        (66,'ANTICUERPOS AC SARS-COV2(IGG IGM)    UNIDAD   RANG',3),
        (67,'ANTICUERPOS SARS-COV2 - ELISA',3),
        (68,'ANTIGENO NASAL SARS-COV2',3),
        (69,'H.A.I. TOXO',3),


        (1,'EXAMEN GRAL.DE ORINA',4),
        (2,'CITOLOGIA URINARIA',4),
        (3,'PROTEINURIA EN ORINA DE 24 HRS.',4),
        (4,'CREATINURIA EN ORINA DE 24 HRS.',4),
        (5,'CLEARENCE DE CREATININA EN ORINA DE 24 HRS.',4),
        (6,'ACIDO URICO EN ORINA DE 24 HRS.',4),
        (8,'DISMORFISMO ERITROCITARIO',4),
        (9,'CALCIO EN ORINA DE 24 HRS.',4),
        (10,'DISMORFISMO ERITROCITARIO',4),
        (11,'SODIO EN ORINA DE 24 HRS.',4),
        (12,'POTASIO EN ORINA DE 24 HRS.',4),
        (13,'CLORO EN ORINA DE 24 HRS.',4),
        (14,'PROTEINA DE BENCE JONES',4),
        (15,'SODIO Y POTASIO EN ORINA DE 24 HORAS',4),
        (16,'UREA EN ORINA DE 24 HRS.',4),
        (17,'BK EN ORINA',4),


        (1,'* COPROPARASITOLOGICO',5),
        (2,'* COPROPARASITOLOGICO SERIADO',5),
        (3,'* MOCO FECAL',5),
        (4,'SANGRE OCULTA',5),
        (5,'ANAL SWAB',5),
        (6,'ROTAVIRUS',5),
        (7,'GRUPO SANGUINEO',5),
        (8,'STROUTH',5),
        (9,'SUSTANCIAS REDUCTORAS',5),
        (10,'HELICOBACTER PYLORI',5),
        (11,'SANGRE DE CORDON',5),


        (1,'ANTIGENO AUSTRALIANO',6),
        (2,'SECRECION VAGINAL',6),
        (3,'SECRECIONES',6),
        (4,'LIQUIDOS BIOLOGICOS',6),
        (5,'CITOGRAMA NASAL',6),
        (6,'BASILOSCOPIA SIMPLE',6),
        (7,'BASILOSCOPIA SERIADO',6),
        (8,'COPROCULTIVO',6),
        (9,'SECRECION URETRAL',6),
        (10,'TEST DE CLAMIDIA',6),
        (11,'SECRECIONES PURULENTAS',6),
        (12,'HEMOCULTIVO',6),
        (13,'CULTIVO Y ANTIB.CITOQUIMICO',6),
        (14,'CUL.BACTERIOLOGICO ANTIB.',6),
        (15,'LIQUIDO CEFALORRAQU.+ANTIB.',6),
        (16,'MICOLOGICO',6),
        (17,'UROCULTIVO',6),
        (18,'PROLACTINA',6),
        (19,'SECRECIONES OCULARES',6),
        (20,'CULTIVO',6),
        (21,'ANTIBIOGRAMA',6),
        (22,'ANTIBIOGRAMA URO',6),
        (23,'ANTIBIOGRAMA COPRO',6),
        (24,'ANTIBIOGRAMA SECRECIONES',6),
        (25,'ANTIBIOGRAMA HEMO',6),
        (26,'ANTIBIOGRAMA VAGINAL',6),
        (27,'ANTIBIOGRAMA ADICIONAL',6),


        (1,'PROGESTERONA',7),
        (2,'ESTRADIOL',7),
        (3,'HCG',7),
        (4,'T3',7),
        (5,'T4 TOTAL',7),
        (6,'TSH',7),
        (7,'TESTOSTERONA',7),
        (8,'LH',7),
        (9,'FSH',7),
        (10,'...................',7),
        (11,'T4 LIBRE',7),
        (12,'PSA TOTAL',7),
        (13,'TSH NEONATAL',7),
        (14,'DOSIF.DE CORTISOL',7),
        (15,'FERRITINA',7),
        (16,'DOSF.OSTEOCALCINA',7),
        (17,'PERFIL HORMONAL GINECL.',7),
        (18,'PERFIL TIROIDEO',7),
        (19,'HELICOBACTER PYLORI',7),
        (20,'INSULINA',7),
        (21,'HIERRO SERICO',7),
        (22,'HORMONA DEL CRECIMIENTO(GRH)',7),
        (23,'CA 19.9 (GIMA)',7),
        (24,'TPO',7),
        (25,'IGE',7),
        (26,'ALFA FETO PROTEINAS (AFP)',7),
        (27,'ANTI TPO (ATA ANTIPEROXIDASA)',7),
        (28,'ATG ANTIROGLOBULINA',7),
        (29,'CA 125',7),
        (30,'ESTROGENO',7),
        (31,'CEA',7),
        (32,'CA 15.3',7),
        (33,'ERITROPOYETINA (EPO)',7),
        (34,'TIROGLOBULINA',7),
        (35,'CURVA DE INSULINA',7),
        (36,'INSULINA POST',7),
        (37,'PARATORMONA (IPTH)',7),
        (38,'MIOGLOBINA CANTITATIVO',7),
        (39,'PROLACTINA',7),
        (40,'TROPONINA I CUANTITAVO',7),
        (41,'DHEA SULFATO',7),
        (42,'DOSIF.CORTISOL  16:00',7),
        (43,'VIT  B12',7),
        (44,'...........',7),
        (45,'......',7),
        (46,'PSA LIBRE',7),
        (47,'RELACION PSA LIBRE/PSA TOTAL',7),
        (48,'.............................',7),
        (49,'TSH NEONATAL (LUMATEX)',7),


        (1,'C.PRENATAL',8),
        (2,'EXA.GRAL.ORINA',8),

        (1,'C.PREQUIR.',9),

        (1,'EXA.GRAL.SANGRE',10),
        (2,'EXA.GRAL.ORINA',10),

        (1,'EXA.GRAL.SANGRE',11),
        (2,'EXA.GRAL.ORINA',11),

        (1,'ARN-COVID(RT-PCR TIEMPO REAL)',12),
        (2,'ARN-COVID-19(RT-PCR TIEMPO REAL)',12),
        (3,'ARN-COVID-19(RT-PCR TIEMPO REAL)',12),
        (4,'PANEL RESPIRATORIO',12)";

        DB::statement($scriptlab);
    }
}
